Module_9_Week_24_Lecture_1_Rails_Review/chatty/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :authors do
    resources :books
  end

  namespace :dashboard do
    resources :authors
  end
end

Module_9_Week_24_Lecture_1_Rails_Review/chatty/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Module_9_Week_24_Lecture_1_Rails_Review/chatty/app/models/author.rb
class Author < ApplicationRecord
  has_many :books 
end

Module_9_Week_24_Lecture_1_Rails_Review/chatty/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

Module_9_Week_24_Lecture_1_Rails_Review/chatty/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Module_9_Week_24_Lecture_1_Rails_Review/chatty/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end
end

Module_9_Week_24_Lecture_1_Rails_Review/chatty/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @author = Author.find(params[:author_id])
    @books = @author.books
  end
end

Module_9_Week_24_Lecture_1_Rails_Review/chatty/app/helpers/application_helper.rb
module ApplicationHelper
end

Module_9_Week_24_Lecture_1_Rails_Review/chatty/app/views/authors/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Authors</title>
</head>
<body>
  <h1>All the Authors</h1>
  <% @authors.each do |author| %>
    <div>
      <h2><%= "#{author.first_name} #{author.last_name}" %> - <%= link_to 'Books', author_books_path(author)  %></h2>
    </div>
  <% end %>
</body>
</html>

Module_9_Week_24_Lecture_1_Rails_Review/chatty/app/views/books/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Books</title>
</head>
<body>
  <h2>The Books of <%= "#{@author.first_name} #{@author.last_name}"%></h2>
  <%= link_to 'Home', authors_path  %>
  <% @books.each do |book| %>
    <div>
      <%= book.title %>
    </div>
  <% end %>
</body>
</html>

Module_9_Week_24_Lecture_1_Rails_Review/chatty/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatty</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>